### ISSUE TITLE
Auto vaccinator causes crashes 

### ISSUE THREAD

**Issue by karawaya** [rei-kes/Fedoraware#11]
auto vac causes crashes first time it crashed it issued an client.dll error second time it crashed it just issued nothing. I was trying to test the auto vac in tr_walkway but it just suddenly kept crashing everytime a bot launched an projectile at me or 
A bot using the flame thrower at me. The cheat works fine no crashes or issues whatsoever but for some reason the only thing that causes me to crash is just the auto vac.

**Comment by rei-kes** [comment]
the auto vaccinator is relatively unchanged from the main repo. i plan on rewriting it soon.
