### ISSUE TITLE
Hit chance causes proj aimbot to not shoot or delay shot 

### ISSUE THREAD

**Issue by karawaya** [rei-kes/Fedoraware#12]
Hit chance causes proj aim bot to not shoot or just makes it delayed. No matter the percentage 50% 100% 15% 35% etc etc etc. The steps are easy to reproduce just set ur hit chance to 50 or 30 or whatever  the number. 
and the aimbot will shoot 1 or 2 times and then stop.  or shoot after 5 secs. Or won't shoot at all.

**Comment by phonkv2** [comment]
i think it works fine even if you set your hit chance to 0% i have mine set to 0% i rarely get delayed hits (sim time is 6s) though it does happen

**Comment by karawaya** [comment]
weird. Anything other than 0 percent it just shoots twice or once and then stops or it delays the shot.

**Comment by phonkv2** [comment]
> weird. Anything other than 0 percent it just shoots twice or once and then stops or it delays the shot.

Are you using the latest build of the cheat? try redownloading the dll

**Comment by karawaya** [comment]
I'm. In fact this issue was in the last build as well. But here I'm reporting it now.

**Comment by phonkv2** [comment]
> I'm. In fact this issue was in the last build as well. But here I'm reporting it now.

Try using a diffrent config and see if the issue persists

**Comment by karawaya** [comment]
the issue still persists weird. I created a new config designed for projectile. And it worked fine in tr walkway. But in casual the issue happens. The aimbot shoots 1 and 2 times and stops shooting after that. 
![IMG_20240323_135053](https://github.com/rei-kes/Fedoraware/assets/162474237/33119f4f-3f70-4c50-b14a-06571e948187)

**Comment by karawaya** [comment]
here is my proj aimbot settings.

**Comment by phonkv2** [comment]
> here is my proj aimbot settings. 

tbh im not really sure whats causing the issue here wait for rei kes to reslove it can you try out the config i use and see if you still get the issue you can find it in issue#8 projectile bug 
it will be in a mega link

**Comment by phonkv2** [comment]
> the issue still persists weird. I created a new config designed for projectile. And it worked fine in tr walkway. But in casual the issue happens. The aimbot shoots 1 and 2 times and stops shooting after that. 
> 
> ![IMG_20240323_135053](https://github.com/rei-kes/Fedoraware/assets/162474237/33119f4f-3f70-4c50-b14a-06571e948187)
> 
> 
> 
> 

can you also provide a video so i can see what happens

**Comment by karawaya** [comment]
can't provide videos they are over 10 MB long. And its gonna take ages to upload to stream ables. But I tested  it on my friend and it kept shooting him when he stood still but as soon as he circle starfed it stopped shooting at all ( 100% hit chance) I have the video recorded but it's still uploading and gonna take ages.

**Comment by phonkv2** [comment]
> can't provide videos they are over 10 MB long. And its gonna take ages to upload to stream ables. But I tested it on my friend and it kept shooting him when he stood still but as soon as he circle starfed it stopped shooting at all ( 100% hit chance) I have the video recorded but it's still uploading and gonna take ages.

You can use the site fileditch to upload vidoes https://fileditch.com/ to upload vidoes and do try my config

**Comment by rei-kes** [comment]
hitchance works by comparing the current strafe to velocity history, if the chance is below the hitchance var, it won't shoot
