### ISSUE TITLE
proj aim fps drops

### ISSUE THREAD

**Issue by juvenileandiliketosteal** [rei-kes/Fedoraware#14]
basically, proj aim makes u drop fps, even without the splashbot

arc sim aswell makes you drop to like 1-2 fps when u hold the aimkey (again) not a splashbot issue, however for arc it only happens when the person is not visible (ig too many things being bruteforced at once idk) however for the soldier the proj aim makes u lose fps even if u hold aimkey 40 walls behind people, not sure what causes this honestly cause previous builds worked fine, besides that good work on the project! :D (also if needed i can get u clips)

**Comment by phonkv2** [comment]
For me i expirence this issue on demoman with the arc pred w stickbombs it lags and randomly shoots

**Comment by karawaya** [comment]
Doesn't happen to me even on an 2008 pc. Only thing that causes lag is the sticky bomb prediction. Nothing else. Maybe try decreasing simulation time?

**Comment by rei-kes** [comment]
i fixed arc prediction continuing to run when the target was outside of the range and an issue with sticky prime time, and probably some other issues that will be in the next commit
