### ISSUE TITLE
Random crashes while playing heavy 

### ISSUE THREAD

**Issue by phonkv2** [rei-kes/Fedoraware#15]
exactly what the title says whenever i try to play heavy and i aimbot at mutiple people (mine is 2 max) the game randomly decides to close/crash

**Comment by karawaya** [comment]
happens with sniper aswell

**Comment by SkididSkider** [comment]
uhh maybe because you have a shit pc or cheat problem

**Comment by rei-kes** [comment]
any time fedoraware crashes, there *may* be a crash log that is generated formatted Crash_FW_x.dmp, and, at least for me, they appear in the desktop. if you could send those when they occur that may be useful.

**Comment by phonkv2** [comment]
> any time fedoraware crashes, there *may* be a crash log that is generated formatted Crash_FW_x.dmp, and, at least for me, they appear in the desktop. if you could send those when they occur that may be useful. 

Okay the next time it occurs i will be sending you the file here

**Comment by phonkv2** [comment]
> uhh maybe because you have a shit pc or cheat problem

pc isnt a problem i can run it pretty smoothly cheat problem

**Comment by phonkv2** [comment]
> any time fedoraware crashes, there _may_ be a crash log that is generated formatted Crash_FW_x.dmp, and, at least for me, they appear in the desktop. if you could send those when they occur that may be useful.

[Crash_FW_f851.dmp](https://github.com/rei-kes/Fedoraware/files/14814189/Crash_FW_f851.dmp)

**Comment by godofateris** [comment]
well,maybe its crash of too many visuals. I made a cfg that PROBABLY won’t crash game 
[cfg.zip](https://github.com/rei-kes/Fedoraware/files/14889985/cfg.zip)

**Comment by phonkv2** [comment]
> well,maybe its crash of too many visuals. I made a cfg that PROBABLY won’t crash game 
> 
> [cfg.zip](https://github.com/rei-kes/Fedoraware/files/14889985/cfg.zip)
> 
> 

prolly not a cfg issue tho i will test ur cfg later

**Comment by rei-kes** [comment]
i caught a crash that was occurring with third person crosshair/trace filters that should be fixed in the next commit. i have also been thinking of making a discord server to make it easier to debug issues like this, etc.

**Comment by phonkv2** [comment]
> i caught a crash that was occurring with third person crosshair/trace filters that should be fixed in the next commit. i have also been thinking of making a discord server to make it easier to debug issues like this, etc. 

tbh i agree since talking about bugs here takes a while to reach everyone and even you my discord is subsequential lmk if u need help

**Comment by karawaya** [comment]
> i caught a crash that was occurring with third person crosshair/trace filters that should be fixed in the next commit. i have also been thinking of making a discord server to make it easier to debug issues like this, etc.

+1
