### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by pay2lose2** [rei-kes/Fedoraware#16]
I understand if any of those will not be added or changed, but if they will then it's pretty much appreciated
The screenshots provided are just concepts.

1\. Logs about tagged users
There should be a type of log that would tell player when a tagged user joins, leaves, or has been found in match, for example:
`{name} ( {tag} ) has joined`
`{name} ( {tag} ) has left`
`{name} is flagged as {tag}`
`[Enemy] {name} is flagged as {tag}`
![TN Concept](https://github.com/rei-kes/Fedoraware/assets/121765166/d7d5e509-9ea1-4b60-aa2b-0e4f7076b312)

2\. Re-add Taunt Spin and Spy Warning
I noticed that Taunt Spin and Spy Warnings are missing. (To my knowledge, Spy Warning and Taunt Spin was removed in Stax fork and that's what this repo uses)
Will they be re-added?

3\. Cleaner placements
I noticed that 2 widgets are either empty or used for one thing. How about merging them into other ones?
\- Features from `Logs > Settings` should be moved to `Logs > Logs` to avoid confusion (or just remove widgets from logs tab)
\- `Settings > Conditions` (aka keybinds) should be moved to `Visuals > Menu`

![concept 2 final](https://github.com/rei-kes/Fedoraware/assets/121765166/13375840-b034-499f-9883-29c8a59e6d08)
![Concept 2 final V2](https://github.com/rei-kes/Fedoraware/assets/121765166/f6c5c8d4-7c5b-441c-9739-4293e966edeb)

4\. Better indicator for "Always"
Just like original fedoraware, when you set something to Always, it should be showed as "Always" instead of "None". or maybe perhaps add context menu for keybind modes? (Hold, Toggle, Always)
![Concept 1 Final](https://github.com/rei-kes/Fedoraware/assets/121765166/77200374-ab26-4d2b-9615-904f2efe47f1)
![Concept 1 F Version 2](https://github.com/rei-kes/Fedoraware/assets/121765166/ff6c109b-99b3-4337-93f9-1b6f7f1e5663)

**Comment by rei-kes** [comment]
1. this is already a thing (outside of joining and leaving messages), you can enable it through logs > settings > logging > the logs dropdown
![image](https://github.com/rei-kes/Fedoraware/assets/127288356/cc76e35e-12e6-4c42-9eed-db5c165d28a5)
2. at the current moment i have no plans on readding these, though out of fov arrows can alert for spies
3. i plan on using logs > logs for a console like display of all cheat logs eventually, and settings > conditions for 4. 
4. i am replacing the old keybind options in favor of a condition system which will allow the user to bind pretty much any option to a condition, which can include keys, class type, weapon type, and maybe more in the future
![image](https://github.com/rei-kes/Fedoraware/assets/127288356/198f5dde-1288-4385-bb33-aa54907de591)

**Comment by phonkv2** [comment]
I also reccomend adding a few more features like sticky bomb detonation area like it shows the explosion radius and a feature from ateris v3 "gaza bombing" or sticky spam using ticks

**Comment by rei-kes** [comment]
> I also reccomend adding a few more features like sticky bomb detonation area like it shows the explosion radius and a feature from ateris v3 "gaza bombing" or sticky spam using ticks

this is already a thing if you're willing to hold down the recharge button

https://github.com/rei-kes/Fedoraware/assets/127288356/80555f37-982a-48cf-b336-af853ebce0f7

**Comment by phonkv2** [comment]
> > I also reccomend adding a few more features like sticky bomb detonation area like it shows the explosion radius and a feature from ateris v3 "gaza bombing" or sticky spam using ticks
> 
> 
> 
> this is already a thing if you're willing to hold down the recharge button
> 
> 
> 
> https://github.com/rei-kes/Fedoraware/assets/127288356/80555f37-982a-48cf-b336-af853ebce0f7
> 
> 
> 
> 

ohhh never knew it also worked like that thanks
