### ISSUE TITLE
wtf is this update

### ISSUE THREAD

**Issue by Ragdoll117** [rei-kes/Fedoraware#18]
bro why did you remove the assign keys and replace them with something new

**Comment by Ragdoll117** [comment]
shitstain update

**Comment by Ragdoll117** [comment]
I can't even assign the keys to the features properly, it's not working at all

**Comment by rei-kes** [comment]
i've been meaning to make this change for some time now, this allows more customization and the ability to bind pretty much any var to any key, etc. 

https://github.com/rei-kes/Fedoraware/assets/127288356/e7fc57f3-6bc0-47f1-9f88-4f18704a3def

**Comment by Ragdoll117** [comment]
I cant assign one properly, i made one for the aimbot and the aimbot still shoots

**Comment by rei-kes** [comment]
if you want it to only shoot with the key, set the default value to off

**Comment by Ragdoll117** [comment]
i need a config where everything has already their keys, This is actually hard to configure

**Comment by rei-kes** [comment]
https://cdn.discordapp.com/attachments/1227899542964539432/1228120751517863998/7UkhSsR.fw

**Comment by Ragdoll117** [comment]
its not available for some reason

**Comment by Ragdoll117** [comment]
thanks

**Comment by phonkv2** [comment]
do the old configs not work anymore? is there a way to convert them

**Comment by canedoly** [comment]
for me, the "editing the condition" window doesn't appear, causing me to be stuck in editing mode

**Comment by rei-kes** [comment]
> for me, the "editing the condition" window doesn't appear, causing me to be stuck in editing mode. I also have another issue where indicator text doesn't render until I update the DPI value, but other than that, great update

i've changed the behavior of the edit button to exit if you press on a condition you're already editing. could you send a recording and/or config though

**Comment by karawaya** [comment]
what aim type should I set to default? im trying to make my own cfg cause this config makes the aimbot attack none existent backtrack ticks

**Comment by karawaya** [comment]
what aim type should I set to off ? im trying to make my own cfg cause this config makes the aimbot attack none existent backtrack ticks

**Comment by phonkv2** [comment]
> what aim type should I set to off ? im trying to make my own cfg cause this config makes the aimbot  miss alot

you set the aimbot to off it will shot when you hold the key
