### ISSUE TITLE
DT is not consistent

### ISSUE THREAD

**Issue by Ragdoll117** [rei-kes/Fedoraware#2]
Either peeking from a wall or running to the enemy and blastim them, It sometimes works.

**Comment by canedoly** [comment]
user issue, i use 19 ticks with no anti warp and works like a charm

**Comment by Ragdoll117** [comment]
Even with esp rendering more than 7 players insight it works consistently?

**Comment by canedoly** [comment]
> Even with esp rendering more than 7 players insight it works consistently?

wdym

**Comment by Ragdoll117** [comment]
[cfg.zip](https://github.com/rei-kes/Fedoraware/files/14324555/cfg.zip)

Idk what's wrong with my dt, You can check the problem for yourself

**Comment by canedoly** [comment]
> [cfg.zip](https://github.com/rei-kes/Fedoraware/files/14324555/cfg.zip)
> 
> Idk what's wrong with my dt, You can check the problem for yourself

tested your config and the dt almost never shifted any ticks, don't know what could cause this issue

**Comment by Ragdoll117** [comment]
May I have your cfg? I think whatever's causing the problem will be fixed if I put put the exact parameters as your cfg's dt, either way it may be caused by backtrack or even miscs

**Comment by canedoly** [comment]
> May I have your cfg? I think whatever's causing the problem will be fixed if I put put the exact parameters as your cfg's dt, either way it may be caused by backtrack or even miscs

yeah sure [float.zip](https://github.com/rei-kes/Fedoraware/files/14330898/float.zip)

**Comment by Ragdoll117** [comment]
Sad news, It didn't work, I hoping for it to get fixed.
I even tested it with the default cfg dt

**Comment by rei-kes** [comment]
sorry for the delay, issue with it not shifting should be fixed now
