### ISSUE TITLE
failed tf2_win64.exe error

### ISSUE THREAD

**Issue by YALLO99** [rei-kes/Fedoraware#25]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by phonkv2** [comment]
this cheat is for the x32 bit for now wait until rei kes relases a commit for x64 version and suggest joining the discord server

**Comment by Okie12345** [comment]
TF2 is now 64bits, which means that all cheats will have to receive a very big update in order to work

**Comment by YALLO99** [comment]
![Uploading Untitled.png…]()

**Comment by juvenileandiliketosteal** [comment]
> as of right now rijin is already 64bit and other cheats have to do some work to work on 64bit

they have a fix to use the 32bit client on 64bit servers, they are still porting it

**Comment by pay2lose2** [comment]
Assuming rei will care and continue updating this fork, it will probably take a bit before it's going to work

**Comment by canedoly** [comment]
> Assuming rei will care and continue updating this fork, it will probably take a bit before it's going to work

pretty sure the only things that need updating is all the signatures and calling convention of some hooks and probably some other stuff i'm forgetting about
