### ISSUE TITLE
no aimbot bind me sad pls fix

### ISSUE THREAD

**Issue by RandomTNT** [rei-kes/Fedoraware#28]
**Fedoraware Version Date:**  

## Description: 
Cannot find button to bind aimbot after this PR: https://github.com/rei-kes/Fedoraware/pull/23

## Steps to reproduce:  
- [x ] I am able to consistently reproduce this error

download dll from https://github.com/rei-kes/Fedoraware/pull/23

1. https://github.com/rei-kes/Fedoraware/pull/23 download 
2. inject
3. where aimbot bind

## Additional context 

- [x ] I have included the steps to reproduce to the best I am able to share.

**Comment by phonkv2** [comment]
join discord chink

**Comment by Okie12345** [comment]
https://github.com/Fedoraware/Fedoraware

**Comment by pay2lose2** [comment]
https://github.com/rei-kes/Fedoraware/assets/121765166/da8affa9-0f0b-45f8-9476-5ba24f907e4b

here's a video someone uploaded recently on here, should explain basics to you

**Comment by RandomTNT** [comment]
p2l Its beginning to look a lot like nullcore, random shit is everywhere, untill you look at visuals tab, you dont think the cheat is bad, but after you refuund!

**Comment by progamienr** [comment]
you are fucking retarded, go to conditions and make a bind, edit the bind, go to aimbot, and check autoshoot you fucking retard!!!!!!!!!!!!!!!!!

**Comment by RandomTNT** [comment]
BRO WHY NOT KEEP IT STUPID SIMPLE!!!!!

пн, 29 апр. 2024 г. в 11:52, progamienr ***@***.***>:
