### ISSUE TITLE
Unoptimized

### ISSUE THREAD

**Issue by whenisthedoor** [rei-kes/Fedoraware#3]
The paste is so laggy with players and functions.

**Comment by whenisthedoor** [comment]
also i cant build the new version on commit 70

**Comment by rei-kes** [comment]
> also i cant build the new version on commit 70

you shouldn't need to build, every commit there is a compiled dll within the actions tab

**Comment by whenisthedoor** [comment]
i still cant build it, something is wrong with the bitbuf file
