### ISSUE TITLE
nothings a issue but can you plz like add follow bot or walkbot iff you know how to paste or some shitz

### ISSUE THREAD

**Issue by acapro200** [rei-kes/Fedoraware#30]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by phonkv2** [comment]
hell nah this not lmaobox buddy

**Comment by rei-kes** [comment]
no
