### ISSUE TITLE
i cant find the binds in this menu

### ISSUE THREAD

**Issue by Gergish** [rei-kes/Fedoraware#33]
there they are, i dont how to configure auto-rev or why proj aim try to kms if i aim at ground, how to do anything like in average menu i hate using it cuz i dont see "bind there stupid" button
Sorry for blame, im retarded and cant see shit

**Comment by phonkv2** [comment]
please look at the issues opened and for more info hoin the dsicord

**Comment by FlamingoFlim** [comment]
bruh fuck out of here with this faggot ass shit

**Comment by pay2lose2** [comment]
Since alot of people seem to have an issue with keybinding, i might aswell create a seperate issue for it as a documentation. In the meantime, here's a video on how to do it:

https://github.com/rei-kes/Fedoraware/assets/121765166/e20100e8-31cb-4ebb-ac3d-227bbcb1ab95

**Comment by Gergish** [comment]
> Since alot of people ~seem to have an issue with keybinding~ are being stupid idiots not knowing how to look into other issues, especially ones with "documentation" tag, i might aswell create a seperate issue for it as a documentation. In the meantime, here's a video on how to do it:
> 
>  321995576-8d2f3d13-59ac-4542-b942-ba824e08c1fe.mp4

thank you
