### ISSUE TITLE
does anyobdy know why aimbot sometimes breaks when using the shotgun is it normal or like a config issue

### ISSUE THREAD

**Issue by acapro200** [rei-kes/Fedoraware#34]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by Pandoroeo** [comment]
### <ins>**Please provide your config, fedoraware version, record a video of the issue, and give proper steps to reproduce.**</ins>

The backtrack on the latest version is well bad. Fake latency doesn't work at all. Try using the second to latest version. You can get this by, while on rei-kes fedoraware page, scrolling up. Click "actions" and then clicking the second to top one. You must be logged into github to do this. Alternatively you can download it from [https://github.com/rei-kes/Fedoraware/actions/runs/8727845053/artifacts/1423467487](https://github.com/rei-kes/Fedoraware/actions/runs/8727845053/artifacts/1423467487) Turn fake interp to 0 and fake latency to 195. Save your config and reboot the game to be safe. If it's still shit try lowering hitscan multipoint. 

If it STILL is bad try the third to latest which you can get by scrolling up on this github page --> click actions --> click the fourth link. You can also get it from [https://github.com/rei-kes/Fedoraware/actions/runs/8721214258/artifacts/1421771469](https://github.com/rei-kes/Fedoraware/actions/runs/8721214258/artifacts/1421771469)

If it still doesn't work then config issue or something ¯\_(ツ)_/¯

Fwi: If you want help them provide everything. It's frustrating for developers and people trying to help you. If you ever make a github issue just do everything it asks you. If you did this you probably would have already had a fix.

**Comment by acapro200** [comment]
> ### **Please provide your config, fedoraware version, record a video of the issue, and give proper steps to reproduce.**
> The backtrack on the latest version is well bad. Fake latency doesn't work at all. Try using the second to latest version. You can get this by, while on rei-kes fedoraware page, scrolling up. Click "actions" and then clicking the second to top one. You must be logged into github to do this. Alternatively you can download it from https://github.com/rei-kes/Fedoraware/actions/runs/8727845053/artifacts/1423467487 Turn fake interp to 0 and fake latency to 195. Save your config and reboot the game to be safe. If it's still shit try lowering hitscan multipoint.
> 
> If it STILL is bad try the third to latest which you can get by scrolling up on this github page --> click actions --> click the fourth link. You can also get it from https://github.com/rei-kes/Fedoraware/actions/runs/8721214258/artifacts/1421771469
> 
> If it still doesn't work then config issue or something ¯_(ツ)_/¯
> 
> Fwi: If you want help then provide everything. It's frustrating for developers and people trying to help you when you don't. If you ever make a github issue just do everything it asks you. If you did this you probably would have already had a fix.

nvm i fixed it i had backtrack on and other stuff

**Comment by Pandoroeo** [comment]
> >  **snip**
> 
> nvm i fixed it i had backtrack on and other stuff

Great! Then could you close this issue?
