### ISSUE TITLE
Auto continuos rocket jump

### ISSUE THREAD

**Issue by Rayhangege** [rei-kes/Fedoraware#35]
You know that if you rocket jump and if you about to land then shoot a rocket it will continue the rocket jump, Well im to noob to do this and want this feature to be added to automatically shoot a rocket when youre about to land

**Comment by phonkv2** [comment]
learn to rocket jump

**Comment by NecroShaded** [comment]
He means pogo, but fr just get good tbh

**Comment by Pandoroeo** [comment]
> You know that if you rocket jump and if you about to land then shoot a rocket it will continue the rocket jump, Well im to noob to do this and want this feature to be added to automatically shoot a rocket when youre about to land

1. Go on jump academy and learn to rocket jump
2. How would he go about implementing this? It would require an _impossible_ amount of calculations, work, time, it would tank fps, **AND** bloat the cheat. 
3. What you described is pogoing, again learn to rocket jump it's easy

PS: Learn to use apostrophes :)

**Comment by progamienr** [comment]
please close this

**Comment by AssH0tter** [comment]
bro create the bind for auto rocket jump 💀
