### ISSUE TITLE
DoubleTap doesn't work 

### ISSUE THREAD

**Issue by Gergish** [rei-kes/Fedoraware#37]
it seems like in tapfire mode but its not
Config used: https://cdn.discordapp.com/attachments/1231507270425120769/1238899391448744067/Q1NzFuJ.fw?ex=6640f678&is=663fa4f8&hm=90287aadaadb5430d9167fd770dea9f7744a98e0ffa3adbd591ec5d606bad97a&
bind is "Q" if you want to test it

**Comment by phonkv2** [comment]
tapfire mode depends upon the range you can set the distance to it provide a video evidence as well

**Comment by Gergish** [comment]
> tapfire mode depends upon the range you can set the distance to it provide a video evidence as well

i dont use tapfire at all its just dont fire like "DoubleTap" its just skip ticks and shoot like nothing happen

**Comment by phonkv2** [comment]
> > tapfire mode depends upon the range you can set the distance to it provide a video evidence as well
> 
> i dont use tapfire at all its just dont fire like "DoubleTap" its just skip ticks and shoot like nothing happen

please just send a clip

**Comment by Gergish** [comment]
> > > tapfire mode depends upon the range you can set the distance to it provide a video evidence as well
> > 
> > 
> > i dont use tapfire at all its just dont fire like "DoubleTap" its just skip ticks and shoot like nothing happen
> 
> please just send a clip

wait

**Comment by Gergish** [comment]
> > > tapfire mode depends upon the range you can set the distance to it provide a video evidence as well
> > 
> > 
> > i dont use tapfire at all its just dont fire like "DoubleTap" its just skip ticks and shoot like nothing happen
> 
> please just send a clip

https://cdn.discordapp.com/attachments/1231507270425120769/1238907649614151770/2024-05-12-00-34-22.mp4?ex=6640fe29&is=663faca9&hm=604ea53b39fcea7b7f5e6cfd6bfdf21cb905bd89d1cf708104a369a499fc45ad&

Ok it works but slower than in main build with 20 ticks charge

**Comment by phonkv2** [comment]
how many tricks are you charging?

**Comment by Gergish** [comment]
> how many tricks are you charging?

20 ticks like i do before in main build of fed-hat

**Comment by phonkv2** [comment]
21 is minimum and 24 is max

**Comment by Gergish** [comment]
> 21 is minimum and 24 is max

ok thank you
