### ISSUE TITLE
missing with enabled AA

### ISSUE THREAD

**Issue by Gergish** [rei-kes/Fedoraware#39]

**Comment by Shaba412414** [comment]
Brain damage

**Comment by pay2lose2** [comment]
if you're going to make issue, atleast provide some details

**Comment by Scoutc** [comment]
dumb nigger

**Comment by Gergish** [comment]
> if you're going to make issue, atleast provide some details

i just turn real offset to target and fake to view and start shooting backward a projectiles like bombs and other shit AND not in direction of target, also shooting in sky or floor

**Comment by Gergish** [comment]
> > if you're going to make issue, atleast provide some details
> 
> i just turn real offset to target and fake to view and start shooting backward a projectiles like bombs and other shit AND not in direction of target, also shooting in sky or floor

maybe its config issue but idk that to do with that (main fedora wasn't that issue)

**Comment by pay2lose2** [comment]
> i just turn real offset to target and fake to view and start shooting backward a projectiles like bombs and other shit AND not in direction of target, also shooting in sky or floor

i didn't test that yet but from what i can tell, it shoots from fake position instead. fake shows up for everyone and the server while real only shows for you (but you can't shoot fake), either way why would you use target anti-aim?

**Comment by Gergish** [comment]
> > i just turn real offset to target and fake to view and start shooting backward a projectiles like bombs and other shit AND not in direction of target, also shooting in sky or floor
> 
> ~i didn't test that yet but from what i can tell, it shoots from fake position instead. fake shows up for everyone and the server while real only shows for you (but enemies can't shoot fake), either way why would you use target anti-aim?~ if you're not using aimbot, then no matter what you will do it will always shoot in direction where you are looking, also my question still stands: why would you use target anti-aim?
> 
> if you are trying to make legit aa, then do something like fake forward and real edge or something

i just like how real model rotate
