### ISSUE TITLE
Sometimes passive auto DT recharge dont work

### ISSUE THREAD

**Issue by Gergish** [rei-kes/Fedoraware#41]
also i attach config to test whats wrong with that

**Comment by pay2lose2** [comment]
Could you explain in what scenarios it happens? I managed to get it once and changing passive recharge seemed to help.

Also just to let you know: please extend your FOV circle, unless you play community servers, there's no need to keep it this low

**Comment by phonkv2** [comment]
> also i attach config to test whats wrong with that 
> 
> ### [gergish.zip](https://github.com/rei-kes/Fedoraware/files/15368172/gergish.zip)
> 
> 

what the fuck is passive auto dt passive recharge?

**Comment by pay2lose2** [comment]
> what the fuck is passive auto dt passive recharge?

grabs random tick and recharges your dt with it (for example: setting it to 1 makes it grab one tick from 66 ticks, refilling it in whole 24 seconds, not sure why you would prefer that over "Recharge Ticks")

**Comment by phonkv2** [comment]
> > what the fuck is passive auto dt passive recharge?
> 
> 
> 
> grabs random tick and recharges your dt with it (for example: setting it to 1 makes it grab one tick from 66 ticks, refilling it in whole 24 seconds, not sure why you would prefer that over "Recharge Ticks")

thats called passive recharge he said auto dt wtf nigga

**Comment by pay2lose2** [comment]
> thats called passive recharge he said auto dt wtf nigga

oh

**Comment by phonkv2** [comment]
> > > what the fuck is passive auto dt passive recharge?
> 
> > 
> 
> > grabs random tick and recharges your dt with it (for example: setting it to 1 makes it grab one tick from 66 ticks, refilling it in whole 24 seconds, not sure why you would prefer that over "Recharge Ticks")
> 
> 
> 
> i love then im not stuck in air for 1/3 of second also its feels charging faster than full charge and yep i already set in config i attach dt+passive recharge, i say sometimes it not working well for 2-3 games

are you russian? can u join the discord

**Comment by Gergish** [comment]
> > > > what the fuck is passive auto dt passive recharge?
> > 
> > 
> > > 
> > 
> > 
> > > grabs random tick and recharges your dt with it (for example: setting it to 1 makes it grab one tick from 66 ticks, refilling it in whole 24 seconds, not sure why you would prefer that over "Recharge Ticks")
> > 
> > 
> > i love then im not stuck in air for 1/3 of second also its feels charging faster than full charge and yep i already set in config i attach dt+passive recharge, i say sometimes it not working well for 2-3 games
> 
> are you russian? can u join the discord

yo, that discord man?
