### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by pay2lose2** [rei-kes/Fedoraware#44]
Deleting one of the binds deletes all binds you have

Steps:
1. Create sample binds (at most 5)
2. Delete one of them

https://github.com/rei-kes/Fedoraware/assets/121765166/f5396b87-0806-4513-aab3-fcfedbf713a5

**Comment by phonkv2** [comment]
> Deleting one of the binds deletes all binds you have
> 
> Steps:
> 
> 1. Create sample binds (at most 5)
> 2. Delete one of them
> 
>  hl2_IZQzFWSP5Q.mp4

known bug.
are you in the discord?

**Comment by pay2lose2** [comment]
> known bug. are you in the discord?

was, but thanks for info

**Comment by phonkv2** [comment]
you should join back for a suprise

**Comment by pay2lose2** [comment]
> you should join back for a suprise

![image](https://github.com/rei-kes/Fedoraware/assets/121765166/cfae3737-92cc-43c9-ab0a-83cc05d47556)

**Comment by phonkv2** [comment]
(64 bit beta release of rei-fware)

**Comment by pay2lose2** [comment]
> (64 bit beta release of rei-fware)

wadafak rejoining rn!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! (no)

**Comment by phonkv2** [comment]
lol ur choice 
https://media.discordapp.net/attachments/1227898008373297226/1244003118769770547/Screenshot_2024-05-25_150341.png?ex=665387af&is=6652362f&hm=bad4c7eab5610b8e776bce05fdf6820dea05dee3cec607241fbf7030efa6fb00&=&format=webp&quality=lossless&width=1087&height=630
