### ISSUE TITLE
Small bug dump

### ISSUE THREAD

**Issue by pay2lose2** [rei-kes/Fedoraware#9]
Here's a list of bugs I found when using this fork:
* Real Anti-Aim snaps back to fake (example: real spin and fake edge)
![Video](https://github.com/rei-kes/Fedoraware/assets/121765166/90c2dd31-d825-46ea-998f-c0182707327d)
* Projectile Aimbot is not affected by charge (example: huntsman on high distance) 
* Projectile Trajectory is not affected by charge (example: quickiebomb launcher, it shows where the sticky would go with full charge)
![Image](https://github.com/rei-kes/Fedoraware/assets/121765166/e89d7fa1-2678-4984-a713-85b93afaa3d2)
* Aimbot might lag the game (rare, issue from stax fork)
* Chams and Glow might glitch out or disappear (rare)

Don't get me wrong, this fork is good and I see full potential in it. I also understand if any of those won't get fixed due to specific reasons.

**Comment by pay2lose2** [comment]
The auto release seems to be screwing with the trajectory, with the info you provided it works correctly again.

Enabling "shows server hitboxes" does show spin working on low speed, but the higher it is the more it will jitter. Although I understand that the local model may not be 100% accurate

**Comment by rei-kes** [comment]
> * Real Anti-Aim snaps back to fake (example: real spin and fake edge)

the anti aim visuals aren't entirely accurate, but they are accurate enough that i don't really care to make them any more accurate for the time being. 
> * Projectile Aimbot is not affected by charge (example: huntsman on high distance)
> * Projectile Trajectory is not affected by charge (example: quickiebomb launcher, it shows where the sticky would go with full charge)

i did fuck up the projectile aim for weapons with high velocity but it will be fixed next commit. auto release at 0% is intended to do nothing. 
> * Aimbot might lag the game (rare, issue from stax fork)

max targets affects all aim types (hitscan, projectile, melee) and can be reduced to improve performance, though some parts, like hitscan point scale or some aspects of the projectile aim, are more expensive than i'd like and i may optimize them in the future
> * Chams and Glow might glitch out or disappear (rare)

[#5](https://github.com/rei-kes/Fedoraware/issues/5#issuecomment-1987590314)

**Comment by pay2lose2** [comment]
> > * Real Anti-Aim snaps back to fake (example: real spin and fake edge)
> 
> the anti aim visuals aren't entirely accurate, but they are accurate enough that i don't really care to make them any more accurate for the time being.
> 
> > * Projectile Aimbot is not affected by charge (example: huntsman on high distance)
> > * Projectile Trajectory is not affected by charge (example: quickiebomb launcher, it shows where the sticky would go with full charge)
> 
> i did fuck up the projectile aim for weapons with high velocity but it will be fixed next commit. auto release at 0% is intended to do nothing.
> 
> > * Aimbot might lag the game (rare, issue from stax fork)
> 
> max targets affects all aim types (hitscan, projectile, melee) and can be reduced to improve performance, though some parts, like hitscan point scale or some aspects of the projectile aim, are more expensive than i'd like and i may optimize them in the future
> 
> > * Chams and Glow might glitch out or disappear (rare)
> 
> [#5](https://github.com/rei-kes/Fedoraware/issues/5#issuecomment-1987590314)

Alright good to know 👍

**Comment by pay2lose2** [comment]
Oh and i also want to mention one thing:
In the indicators, choosing ping will make conditions draggable instead
The same goes vice versa, choosing conditions will make ping draggable instead (this isn't really big of an issue but still)

https://github.com/rei-kes/Fedoraware/assets/121765166/ab959681-4da1-4a38-b59e-06d7a2c5af50

**Comment by rei-kes** [comment]
> Oh and i also want to mention one thing: In the indicators, choosing ping will make conditions draggable instead The same goes vice versa, choosing conditions will make ping draggable instead (this isn't really big of an issue but still)

whoops haha, thanks for letting me know

**Comment by pay2lose2** [comment]
I also want to mention something about priorities: they are very janky.

If you have someone set on higher priority (example: cheater), as soon as that person gets rendered, you won't be able to shoot any other person that's on lower priority with aimbot (So if you have someone marked as cheater in a casual match, aimbot won't target legits)

(i would show some kind of video but i can't)

**Comment by canedoly** [comment]
> I also want to mention something about priorities: they are very janky.
> 
> If you have someone set on higher priority (example: cheater), as soon as that person gets rendered, you won't be able to shoot any other person that's on lower priority with aimbot (So if you have someone marked as cheater in a casual match, aimbot won't target legits)
> 
> (i would show some kind of video but i can't)

increase max targets

**Comment by rei-kes** [comment]
> I also want to mention something about priorities: they are very janky.
> 
> If you have someone set on higher priority (example: cheater), as soon as that person gets rendered, you won't be able to shoot any other person that's on lower priority with aimbot (So if you have someone marked as cheater in a casual match, aimbot won't target legits)
> 
> (i would show some kind of video but i can't)

i've changed it to only prioritize within max targets rather than all players
